{
 "title": "Kubernetes / Local Persistent Volumes",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "volume",
    "label": "PersistentVolumeClaim",
    "query": {
     "query": "label_values(local_volume_stats_used_bytes{ }, persistentvolumeclaim)"
    }
   }
  ]
 },
 "panels": [
  { "title": "PVC Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Volume Space Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * local_volume_stats_used_bytes{persistentvolumeclaim=\"$volume\"} / ignoring(job)local_volume_stats_capacity_bytes{persistentvolumeclaim=\"$volume\"}"
    }
   ]
  },
  {
   "title": "Volume Space Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "local_volume_stats_used_bytes{persistentvolumeclaim=\"$volume\"}\n\n",
     "legendFormat": "$volume"
    }
   ]
  },
  {
   "title": "Volume Capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "local_volume_stats_capacity_bytes{persistentvolumeclaim=\"$volume\"}",
     "legendFormat": "$volume"
    }
   ]
  },
  {
   "title": "General View",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Space Usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * sum(local_volume_stats_used_bytes{}) / ignoring(job) sum(local_volume_stats_capacity_bytes{})"
      }
     ]
    },
    {
     "title": "Volume Space Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 6, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "local_volume_stats_used_bytes{}\n\n",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Volume Capacity",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "local_volume_stats_capacity_bytes",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Total Space Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 13, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(local_volume_stats_used_bytes{})\n\n",
       "legendFormat": "Total Usage"
      }
     ]
    },
    {
     "title": "Total Volume Claim",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 13, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(local_volume_stats_capacity_bytes{})\n\n",
       "legendFormat": "Total Volume Claim"
      }
     ]
    }
   ]
  }
 ]
}